---
driver:
  name: proxy
  host: localhost
  reset_command: "exit 0"
  port: 5985
  username: <%= ENV["machine_user"] %>
  password: <%= ENV["machine_pass"] %>

provisioner:
  name: chef_zero
  client_rb:
    chef_license: accept

platforms:
  - name: windows-2012r2
    driver:
      box: tas50/windows_2012r2  
#  - name: windows-2016
#    driver:
#      box: tas50/windows_2016
#      customize:
#        memory: 3072
#  - name: windows-2019
#    driver:
#      box: tas50/windows_2016
#      customize:
#        memory: 3072

#verifier:
#  name: inspec

suites:
  - name: agent
    run_list:
      - recipe[sensu_test::agent]
    verifier:
      inspec_tests:
        - test/integration/agent
    attributes:
#  - name: remove-agent
#    run_list:
#      - recipe[sensu_test::agent]      
#      - recipe[sensu_test::remove_agent]
#    verifier:
#      inspec_tests:
#        - test/integration/remove_agent
#    attributes:          
